CREATE DATABASE library;
USE library;

CREATE TABLE authors (
     id INT AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(255)
);

INSERT INTO authors (name) VALUES
('F. Scott Fitzgerald'),
('Harper Lee'),
('George Orwell'),
('J.D. Salinger'),
('J.R.R. Tolkien'),
('John Steinbeck'),
('Karl Marx'),
('William Shakespeare'),
('Fyodor Dostoevsky'),
('Leo Tolstoy'),
('Agatha Christie'),
('William Golding');

CREATE TABLE books (
   id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
   name VARCHAR(255) NOT NULL,
   author_id INT NOT NULL DEFAULT 1,
   image_url VARCHAR(255) NOT NULL,
   release_date DATE NOT NULL,
   availability ENUM('Available', 'Not Available') DEFAULT 'Available' NOT NULL,
   count INT DEFAULT 1 NOT NULL,
   about TEXT NOT NULL,
   FOREIGN KEY (author_id) REFERENCES authors(id)
);

INSERT INTO books (name, author_id, image_url, release_date, count, about) VALUES
('The Great Gatsby', 1, "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg/1024px-The_Great_Gatsby_Cover_1925_Retouched.jpg", '1925-04-10', 12, 'The Great Gatsby, F. Scott Fitzgerald''s third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted "gin was the national drink and sex the national obsession," it is an exquisitely crafted tale of America in the 1920s.'),
('To Kill a Mockingbird', 2, "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg/1024px-To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg", '1960-07-11', 3, 'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. "To Kill A Mockingbird" became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic. Compassionate, dramatic, and deeply moving, "To Kill A Mockingbird" takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.'),
('1984', 3, "https://upload.wikimedia.org/wikipedia/en/5/51/1984_first_edition_cover.jpg", '1949-06-08', 5, 'A masterpiece of rebellion and imprisonment where war is peace freedom is slavery and Big Brother is watching Thought Police Big Brother Orwellian These words have entered our vocabulary because of George Orwell s classic dystopian novel 1984 The story of one man s nightmare odyssey as he pursues a forbidden love affair through a world ruled by warring states and a power structure that controls not only information but also individual thought and memory 1984 is a prophetic haunting tale More relevant than ever before 1984 exposes the worst crimes imaginable the destruction of truth freedom and individuality With a foreword by Thomas Pynchon With a foreword by Thomas Pynchon A masterpiece of rebellion and imprisonment where war is peace freedom is slavery and Big Brother is watching View our feature on George Orwell s 1984 Thought Police Big Brother Orwellian These words have entered our vocabulary because of George Orwell s classic dystopian novel 1984 The story of one man s nightmare odyssey as he pursues a forbidden love affair through a world ruled by warring states and a power structure that controls not only information but also individual thought and memory 1984 is a prophetic haunting tale More relevant than ever before 1984 exposes the worst crimes imaginable the destruction of truth freedom and individuality This beautiful paperback edition features deckled edges and french flaps a perfect gift for any occasion'),
('The Catcher in the Rye', 4, "https://upload.wikimedia.org/wikipedia/commons/8/89/The_Catcher_in_the_Rye_%281951%2C_first_edition_cover%29.jpg", '1951-07-16', 8, 'Fleeing the crooks at Pencey Prep, he pinballs around New York City seeking solace in fleeting encounters—shooting the bull with strangers in dive hotels, wandering alone round Central Park, getting beaten up by pimps and cut down by erstwhile girlfriends. The city is beautiful and terrible, in all its neon loneliness and seedy glamour, its mingled sense of possibility and emptiness. Holden passes through it like a ghost, thinking always of his kid sister Phoebe, the only person who really understands him, and his determination to escape the phonies and find a life of true meaning. The Catcher in the Rye is an all-time classic in coming-of-age literature- an elegy to teenage alienation, capturing the deeply human need for connection and the bewildering sense of loss as we leave childhood behind. J.D. Salinger''s (1919–2010) classic novel of teenage angst and rebellion was first published in 1951. The novel was included on Time''s 2005 list of the 100 best English-language novels written since 1923. It was named by Modern Library and its readers as one of the 100 best English-language novels of the 20th century. It has been frequently challenged in the court for its liberal use of profanity and portrayal of sexuality and in the 1950''s and 60''s it was the novel that every teenage boy wants to read.'),
('The Hobbit', 5, "https://upload.wikimedia.org/wikipedia/en/4/4a/TheHobbit_FirstEdition.jpg", '1937-09-21', 19, 'In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort. Written for J.R.R. Tolkien’s own children, The Hobbit met with instant critical acclaim when it was first published in 1937. Now recognized as a timeless classic, this introduction to the hobbit Bilbo Baggins, the wizard Gandalf, Gollum, and the spectacular world of Middle-earth recounts of the adventures of a reluctant hero, a powerful and dangerous ring, and the cruel dragon Smaug the Magnificent. The text in this 372-page paperback edition is based on that first published in Great Britain by Collins Modern Classics (1998), and includes a note on the text by Douglas A. Anderson (2001).'),
('The Lord of the Rings', 5, "https://upload.wikimedia.org/wikipedia/en/e/e9/First_Single_Volume_Edition_of_The_Lord_of_the_Rings.gif", '1954-07-29', 2, 'In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell by chance into the hands of the hobbit Bilbo Baggins. From Sauron''s fastness in the Dark Tower of Mordor, his power spread far and wide. Sauron gathered all the Great Rings to him, but always he searched for the One Ring that would complete his dominion. When Bilbo reached his eleventy-first birthday he disappeared, bequeathing to his young cousin Frodo the Ruling Ring and a perilous quest: to journey across Middle-earth, deep into the shadow of the Dark Lord, and destroy the Ring by casting it into the Cracks of Doom. The Lord of the Rings tells of the great quest undertaken by Frodo and the Fellowship of the Ring: Gandalf the Wizard; the hobbits Merry, Pippin, and Sam; Gimli the Dwarf; Legolas the Elf; Boromir of Gondor; and a tall, mysterious stranger called Strider.'),
('The Grapes of Wrath', 6, "https://upload.wikimedia.org/wikipedia/commons/a/ad/The_Grapes_of_Wrath_%281939_1st_ed_cover%29.jpg", '1939-04-14', 4, 'The Pulitzer Prize-winning epic of the Great Depression, a book that galvanized—and sometimes outraged—millions of readers. First published in 1939, Steinbeck’s Pulitzer Prize-winning epic of the Great Depression chronicles the Dust Bowl migration of the 1930s and tells the story of one Oklahoma farm family, the Joads—driven from their homestead and forced to travel west to the promised land of California. Out of their trials and their repeated collisions against the hard realities of an America divided into Haves and Have-Nots evolves a drama that is intensely human yet majestic in its scale and moral vision, elemental yet plainspoken, tragic but ultimately stirring in its human dignity. A portrait of the conflict between the powerful and the powerless, of one man’s fierce reaction to injustice, and of one woman’s stoical strength, the novel captures the horrors of the Great Depression and probes into the very nature of equality and justice in America. At once a naturalistic epic, captivity narrative, road novel, and transcendental gospel, Steinbeck’s powerful landmark novel is perhaps the most American of American Classics.'),
('The Pearl', 6, "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/The_Pearl_%281947_1st_ed_dust_jacket%29.jpg/800px-The_Pearl_%281947_1st_ed_dust_jacket%29.jpg", '1947-11-08', 7, 'Like his father and grandfather before him, Kino is a poor diver, gathering pearls from the gulf beds that once brought great wealth to the kings of Spain and now provide Kino, Juana, and their infant son with meager subsistence. Then, on a day like any other, Kino emerges from the sea with a pearl as large as a sea gull’s egg, as “perfect as the moon.” With the pearl comes hope, the promise of comfort and of security… A story of classic simplicity, based on a Mexican folk tale, The Pearl explores the secrets of man’s nature, greed, the darkest depths of evil, and the luminous possibilities of love.'),
('Das Kapital', 7, "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Zentralbibliothek_Z%C3%BCrich_Das_Kapital_Marx_1867.jpg/800px-Zentralbibliothek_Z%C3%BCrich_Das_Kapital_Marx_1867.jpg", '1867-09-14', 8, 'Das Kapital, Karl Marx''s seminal work, is the book that above all others formed the twentieth century. From Kapital sprung the economic and political systems that at one time dominated half the earth and for nearly a century kept the world on the brink of war. Even today, more than one billion Chinese citizens live under a regime that proclaims fealty to Marxist ideology. Yet this important tome has been passed over by many readers frustrated by Marx’s difficult style and his preoccupation with nineteenth-century events of little relevance to today''s reader. Here Serge Levitsky presents a revised version of Kapital, abridged to emphasize the political and philosophical core of Marx’s work while trimming away much that is now unimportant. Pointing out Marx’s many erroneous predictions about the development of capitalism, Levitsky''s introduction nevertheless argues for Kapital''s relevance as a prime example of a philosophy of economic determinism that "subordinates the problems of human freedom and human dignity to the issues of who should own the means of production and how wealth should be distributed." Here then is a fresh and highly readable version of a work whose ideas provided inspiration for communist regimes'' ideological war against capitalism, a struggle that helped to shape the world today.'),
('The Communist Manifesto', 7, "https://upload.wikimedia.org/wikipedia/commons/8/86/Communist-manifesto.png", '1848-02-21', 1, 'Originally published on the eve of the 1848 European revolutions, The Communist Manifesto is a condensed and incisive account of the worldview Marx and Engels developed during their hectic intellectual and political collaboration. Formulating the principles of dialectical materialism, they believed that labor creates wealth, hence capitalism is exploitive and antithetical to freedom. This new edition includes an extensive introduction by Gareth Stedman Jones, Britain''s leading expert on Marx and Marxism, providing a complete course for students of The Communist Manifesto, and demonstrating not only the historical importance of the text, but also its place in the world today. For more than seventy years, Penguin has been the leading publisher of classic literature in the English-speaking world. With more than 1,700 titles, Penguin Classics represents a global bookshelf of the best works throughout history and across genres and disciplines. Readers trust the series to provide authoritative texts enhanced by introductions and notes by distinguished scholars and contemporary authors, as well as up-to-date translations by award-winning translators.'),
('Hamlet', 8, "https://upload.wikimedia.org/wikipedia/commons/d/df/Hamlet.jpg", '1603-01-01', 20, 'Among Shakespeare''s plays, "Hamlet" is considered by many his masterpiece. Among actors, the role of Hamlet, Prince of Denmark, is considered the jewel in the crown of a triumphant theatrical career. Now Kenneth Branagh plays the leading role and co-directs a brillant ensemble performance. Three generations of legendary leading actors, many of whom first assembled for the Oscar-winning film "Henry V", gather here to perform the rarely heard complete version of the play. This clear, subtly nuanced, stunning dramatization, presented by The Renaissance Theatre Company in association with "Bbc" Broadcasting, features such luminaries as Sir John Gielgud, Derek Jacobi, Emma Thompson and Christopher Ravenscroft. It combines a full cast with stirring music and sound effects to bring this magnificent Shakespearen classic vividly to life. Revealing new riches with each listening, this production of "Hamlet" is an invaluable aid for students, teachers and all true lovers of Shakespeare - a recording to be treasured for decades to come.'),
('Crime and Punishment', 9, "https://upload.wikimedia.org/wikipedia/en/4/4b/Crimeandpunishmentcover.png", '1866-01-01', 6, 'Raskolnikov, a destitute and desperate former student, wanders through the slums of St Petersburg and commits a random murder without remorse or regret. He imagines himself to be a great man, a Napoleon: acting for a higher purpose beyond conventional moral law. But as he embarks on a dangerous game of cat and mouse with a suspicious police investigator, Raskolnikov is pursued by the growing voice of his conscience and finds the noose of his own guilt tightening around his neck. Only Sonya, a downtrodden sex worker, can offer the chance of redemption.'),
('War and Peace', 10, "https://upload.wikimedia.org/wikipedia/commons/a/af/Tolstoy_-_War_and_Peace_-_first_edition%2C_1869.jpg", '1869-01-01', 5, 'In Russia''s struggle with Napoleon, Tolstoy saw a tragedy that involved all mankind. War and Peace broadly focuses on Napoleon’s invasion of Russia in 1812 and follows three of the most well-known characters in literature: Pierre Bezukhov, the illegitimate son of a count who is fighting for his inheritance and yearning for spiritual fulfillment; Prince Andrei Bolkonsky, who leaves his family behind to fight in the war against Napoleon; and Natasha Rostov, the beautiful young daughter of a nobleman who intrigues both men. As Napoleon’s army invades, Tolstoy brilliantly follows characters from diverse backgrounds—peasants and nobility, civilians and soldiers—as they struggle with the problems unique to their era, their history, and their culture. And as the novel progresses, these characters transcend their specificity, becoming some of the most moving—and human—figures in world literature. Tolstoy gave his personal approval to this translation, published here in a new single volume edition, which includes an introduction by Henry Gifford, and Tolstoy''s important essay `Some Words about War and Peace.'),
('And Then There Were None', 11, "https://upload.wikimedia.org/wikipedia/en/4/4a/And_Then_There_Were_None_First_Edition_Cover_1939.jpg", '1939-01-01', 3, 'First, there were ten—a curious assortment of strangers summoned as weekend guests to a little private island off the coast of Devon. Their host, an eccentric millionaire unknown to all of them, is nowhere to be found. All that the guests have in common is a wicked past they''re unwilling to reveal—and a secret that will seal their fate. For each has been marked for murder. A famous nursery rhyme is framed and hung in every room of the mansion: "Ten little boys went out to dine; One choked his little self and then there were nine. Nine little boys sat up very late; One overslept himself and then there were eight. Eight little boys traveling in Devon; One said he''d stay there then there were seven. Seven little boys chopping up sticks; One chopped himself in half and then there were six. Six little boys playing with a hive; A bumblebee stung one and then there were five. Five little boys going in for law; One got in Chancery and then there were four. Four little boys going out to sea; A red herring swallowed one and then there were three. Three little boys walking in the zoo; A big bear hugged one and then there were two. Two little boys sitting in the sun; One got frizzled up and then there was one. One little boy left all alone; He went out and hanged himself and then there were none." When they realize that murders are occurring as described in the rhyme, terror mounts. One by one they fall prey. Before the weekend is out, there will be none. Who has choreographed this dastardly scheme? And who will be left to tell the tale? Only the dead are above suspicion.'),
('Lord of the Flies', 12, "https://upload.wikimedia.org/wikipedia/en/9/9b/LordOfTheFliesBookCover.jpg", '1954-01-01', 21, 'At the dawn of the next world war, a plane crashes on an uncharted island, stranding a group of schoolboys. At first, with no adult supervision, their freedom is something to celebrate; this far from civilization the boys can do anything they want. Anything. They attempt to forge their own society, failing, however, in the face of terror, sin and evil. And as order collapses, as strange howls echo in the night, as terror begins its reign, the hope of adventure seems as far from reality as the hope of being rescued. Labeled a parable, an allegory, a myth, a morality tale, a parody, a political treatise, even a vision of the apocalypse, Lord of the Flies is perhaps our most memorable novel about “the end of innocence, the darkness of man’s heart.”'),
('The Secret Adversary', 11, "https://upload.wikimedia.org/wikipedia/en/0/03/Secret_Adversary_First_Edition_Cover_1922.jpg", '1922-01-01', 4, 'Tommy Beresford and Prudence ''Tuppence'' Cowley are young, in love… and flat broke. Just after Great War, there are few jobs available and the couple are desperately short of money. Restless for excitement, they decide to embark on a daring business scheme: Young Adventurers Ltd.—"willing to do anything, go anywhere." Hiring themselves out proves to be a smart move for the couple. In their first assignment for the mysterious Mr. Whittingtont, all Tuppence has to do in their first job is take an all-expense paid trip to Paris and pose as an American named Jane Finn. But with the assignment comes a bribe to keep quiet, a threat to her life, and the disappearance of her new employer. Now their newest job are playing detective. Where is the real Jane Finn? The mere mention of her name produces a very strange reaction all over London. So strange, in fact, that they decided to find this mysterious missing lady. She has been missing for five years. And neither her body nor the secret documents she was carrying have ever been found. Now post-war England''s economic recovery depends on finding her and getting the papers back. But he two young working undercover for the British ministry know only that her name and the only photo of her is in the hands of her rich American cousin. It isn’t long before they find themselves plunged into more danger than they ever could have imagined—a danger that could put an abrupt end to their business… and their lives.');



CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    permission_level INT DEFAULT 0 NOT NULL
);

INSERT INTO users (username, password, email, permission_level) VALUES
('admin', '$2y$10$LXrs1zxgg.bc1TK7rugWcuJSClBRM54wc45IA5orWsYG.7pFRSm9m', 'admin@books.com', 1);
-- password: root

CREATE TABLE borrowed_books (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    user_id INT NOT NULL,
    book_id INT NOT NULL,
    count INT DEFAULT 1 NOT NULL,
    borrow_date DATE NOT NULL,
    return_date DATE NOT NULL,
    status ENUM('borrowing', 'returned') DEFAULT 'borrowing',
    foreign key (user_id) references users(id),
    foreign key (book_id) references books(id)
);

